name: znn_controller_dart
description: Zenon Node Controller
version: 0.0.4
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^3.0.2
  dart_ipify: ^1.1.1
  system_info2: ^4.0.0
  random_string_generator: ^2.0.0
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: f3adff23fa6af3882b25bfb8a1d157f04f8a7b5d

dev_dependencies:
  test: ^1.17.9
  lints: ^2.0.1
